#google_assistant:
project_id: mr-nikt    
client_id: !secret google_client_id
access_token: !secret google_access_token
agent_user_id: !secret icloud_usr_1
exposed_domains:
 - switch
 - light
 - fan
 - scene
 - script
 - climate
 - vacuum
