## https://home-assistant.io/components/logger/
## critical fatal error warning warn info debug notset

  default: warning
  logs:
    homeassistant.setup: fatal
    homeassistant.loader: fatal
    homeassistant.core: fatal
    homeassistant.components.sensor: fatal
#    homeassistant.components.media_player.spotify: info
    homeassistant.components.media_player.sonytv: info
    homeassistant.helpers.template: fatal
    homeassistant.helpers.entity: fatal
    
#    netdisco.ssdp: fatal
#    homeassistant.components.telegram_bot.polling: error
#   homeassistant.components.device_tracker.mqtt: warning
#    homeassistant.components.websocket_api: warning
